services:
  db:
    build: .
    container_name: prismaapi-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    env_file:
      - .env

  dbtest:
    build: .
    container_name: test-db
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env
